# Generated by Django 3.1.3 on 2022-07-30 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_grade',
            new_name='grade',
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=550, null=True),
        ),
    ]
